### ISSUE TITLE
Three.js landing page - Truck navigation using keyboard

### ISSUE THREAD

**Issue by dance2die** [sw-yx/spark-joy#12]
https://bruno-simon.com/

![aVH9FTqL4N](https://user-images.githubusercontent.com/8465237/67625449-7ce21c80-f80c-11e9-90be-91653dc9b4f3.gif)

**Comment by sw-yx** [comment]
thanks, but not drop-in enough. does inspire people tho.

**Comment by dance2die** [comment]
It didn't fit the goal of the repo 😝.
