### ISSUE TITLE
Curated colors in context

### ISSUE THREAD

**Issue by dance2die** [sw-yx/spark-joy#13]
Provides a nice set of color combinations for sites.
https://www.happyhues.co/

![H3IFuRGV0o](https://user-images.githubusercontent.com/8465237/70828130-c258aa00-1db8-11ea-81dd-6eabe7a62054.gif)

**Comment by sw-yx** [comment]
already added, thx

**Comment by dance2die** [comment]
Ah,.. ma bad & thx
