### ISSUE TITLE
Proxima Nova listed in free fonts section, it's not free

### ISSUE THREAD

**Issue by edadams** [sw-yx/spark-joy#22]
I don't know if I've misunderstood the free fonts section at the very top, but Chivo is free and Proxima Nova isn't. It's on Typekit and available for purchase in lots of different ways, but the wording seems accidentally misleading there. I thought I should open an issue to let you know. 

A few other really good free fonts if you want something to go there instead (expect you already know about these, but just trying to give some ideas for actually free fonts):

- [Lato ](http://www.latofonts.com/)(Quite well known but very readable and pretty. Anecdote: In my web designs when I show clients a choice of fonts Lato gets picked a lot.)
- [Libre Franklin](https://beautifulwebtype.com/libre-franklin/) (Overlooked, pretty elegant and thin.)
- [IBM Plex Sans](https://www.ibm.com/plex/) (I think this one is worth promoting. There's loads of weights and it's really beautifully done in my opinion. Very much overlooked.)
- [Clear Sans](https://01.org/clear-sans) (Also lesser known and really good.)

I'm not aware of these in use on "real" websites to such an extent that they'd make a good demo, so understand if that's a problem.

Hopefully this is helpful!

**Comment by sw-yx** [comment]
excellent! thank you very much! no i actually didnt do a ton of due diligence there, since i dont do a lot of client work, i just peek into the font stack of sites i like and do a quick google to guess if they're free or not. i'll update accordingly. cheers mate! also inviting you to contribute
