### ISSUE TITLE
khroma.co

### ISSUE THREAD

**Issue by hasparus** [sw-yx/spark-joy#24]
> - http://khroma.co/ neural network generated color palettes

khroma is pretty cool, but I'm not sure if it's _cool enough_

![image](https://user-images.githubusercontent.com/15332326/72372094-04517480-3706-11ea-8043-d59dc78f82c2.png)
![image](https://user-images.githubusercontent.com/15332326/72372174-29de7e00-3706-11ea-8c71-9f6ba9eda4ff.png)

**Comment by sw-yx** [comment]
it is pretty cool! i reckon its more of a toy but worth adding
