### ISSUE TITLE
Single Element CSS Spinners

### ISSUE THREAD

**Issue by dance2die** [sw-yx/spark-joy#30]
**Home**: https://projects.lukehaas.me/css-loaders/
**Source**: https://github.com/lukehaas/css-loaders
**License**: MIT - https://github.com/lukehaas/css-loaders/blob/step2/LICENSE

## Suggestion

Add under - https://github.com/sw-yx/spark-joy/#spinners

**Comment by sw-yx** [comment]
SGTM!

**Comment by dance2die** [comment]
Ma bad. I pushed to the master instead of doing a PR.  
Please undo if uncalled for...

**Comment by sw-yx** [comment]
np!
