### ISSUE TITLE
microsoft/fluentui-system-icons - MIT licensed SVG icons

### ISSUE THREAD

**Issue by dance2die** [sw-yx/spark-joy#33]
**Source**: https://github.com/microsoft/fluentui-system-icons
**Icons**: https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md

Can we add it under https://github.com/sw-yx/spark-joy/blob/master/README.md#icons-and-favicons ?

**Comment by sw-yx** [comment]
added. thanks!
