### ISSUE TITLE
layout practice

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/spark-joy#4]
https://tympanus.net/codrops/2019/06/04/inspirational-websites-roundup-5/

http://every-layout.dev

**Comment by beatgrabe** [comment]
I am confused about every-layout.dev, because there are sections you have to pay for?!

**Comment by edadams** [comment]
From [its website](https://every-layout.dev/blog/you-pay/):

>large selection of free content, including all of the “rudiment” articles that cover the basics of (our take on) contemporary CSS

You only have to pay if you want a very comprehensive version.

I think it looks cool as hell. @sw-yx: May I ask what stopped you from adding this?

**Comment by sw-yx** [comment]
nothing, i was just on mobile at the time 😅  and i dont think i had a layout section back then. its added now

**Comment by bboydflo** [comment]
what about https://csslayout.io/?

**Comment by sw-yx** [comment]
ooh, i like this! adding. thanks @bboydflo
