### ISSUE TITLE
augmented ui

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/spark-joy#9]
http://augmented-ui.com/

**Comment by James0x57** [comment]
+1 

cheesy, futuristic, super flexible, open source, <sub><sup>and also I made it</sup></sub> 😄

![image](https://user-images.githubusercontent.com/7545075/98311875-143c8c80-1f96-11eb-83a0-60274c2e0338.png)

**Comment by sw-yx** [comment]
haha nice!! thank you for making such a cool framework. i likely added this issue while i was on my phone (hard to edit markdown) - ill go add it now

**Comment by sw-yx** [comment]
done https://github.com/sw-yx/spark-joy/commit/6e46560d61924f9e4b5d1409cf57b0515400697b
